using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ThesisRepository.Models
{
    // Maps to PasswordResetRequests table — created via 2_AlterDatabase.sql or by DbInitializer
    [Table("PasswordResetRequests")]
    public class PasswordResetRequest
    {
        // NVARCHAR(450) PRIMARY KEY  — GUID string generated by C# code
        [Key]
        [MaxLength(450)]
        [Column("Id")]
        public string Id { get; set; } = Guid.NewGuid().ToString();

        // NVARCHAR(255) NOT NULL
        [Required]
        [EmailAddress]
        [MaxLength(255)]
        [Column("Email")]
        public string Email { get; set; } = string.Empty;

        // NVARCHAR(50) NOT NULL DEFAULT 'pending'
        [Required]
        [MaxLength(50)]
        [Column("Status")]
        public string Status { get; set; } = "pending";

        // DATETIME2 NOT NULL DEFAULT GETUTCDATE()
        [Column("RequestedAt")]
        public DateTime RequestedAt { get; set; } = DateTime.UtcNow;

        // DATETIME2 - nullable
        [Column("ProcessedAt")]
        public DateTime? ProcessedAt { get; set; }

        // NVARCHAR(255) - nullable
        [MaxLength(255)]
        [Column("ProcessedBy")]
        public string? ProcessedBy { get; set; }
    }
}
